### ISSUE TITLE
[VIT] Cordova plugin

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/chain-wallet-libs#31]
Still some unknowns but there is a tutorial about it there: https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/

- [x] ios
- [x] android #36 
- [x] electron #48

**Comment by enzoc4** [comment]
Just to keep track of things. Maybe this would look better as a table, but it seems (interactive) checkboxes don't work inside.

# Android

- [X] walletRestore
- [X] walletRetrieveFunds
- [X] walletTotalFunds
- [X] walletId
- [ ] walletSetState (#61)
- [X] walletConvert
- [X] conversionTransactionsSize
- [X] conversionTransactionsGet
- [ ] conversionGetIgnored (#61)
- [X] walletDelete
- [X] settingsDelete
- [X] conversionDelete

# Electron

- [X] walletRestore
- [X] walletRetrieveFunds
- [X] walletTotalFunds
- [X] walletId
- [ ] walletSetState (#61)
- [X] walletConvert
- [X] conversionTransactionsSize
- [X] conversionTransactionsGet
- [ ] conversionGetIgnored (#61)
- [X] walletDelete
- [X] settingsDelete
- [X] conversionDelete

# IOS

- [ ] walletRestore (#59)
- [ ] walletRetrieveFunds (#59)
- [ ] walletTotalFunds (#59)
- [ ] walletId (#59)
- [ ] walletSetState
- [ ] walletConvert
- [ ] conversionTransactionsSize
- [ ] conversionTransactionsGet
- [ ] conversionGetIgnored
- [ ] walletDelete (#59)
- [ ] settingsDelete (#59)
- [ ] conversionDelete

**Comment by eugene-babichenko** [comment]
@enzoc4 could you please udpate your comment? Conversion functions also were added in #59.

**Comment by enzoc4** [comment]
closed as this set of features is already implemented, it's better to use new issues for the new things.
