### ISSUE TITLE
JS bindings: improve the panic hook handling

### ISSUE THREAD

**Issue by NicolasDP** [input-output-hk/chain-wallet-libs#54]
`bindings/wallet-js/src/utils.rs#L1`
function is never used: `set_panic_hook`.

It may be that the library raise a panic. We need to be able to hook it so we can propagate a more meaningful error where appropriate.

**Comment by enzoc4** [comment]
I'm not really sure how is that supposed to handled, tbh. We could call the function at the top of `Wallet::recover` as that's the only entry point of the library. We could also expose an `initialize` function or something and leave it to the user, I think. I'm not sure why the code generator doesn't automatically include a call to that, actually.

**Comment by NicolasDP** [comment]
expose the function for the library to call
